resilience4j:
  retry:
    instances:
      serviceBRetry:
        max-attempts: 10
        wait-duration: 2s
        retry-exceptions:
          - org.springframework.web.client.ResourceAccessException